### ISSUE TITLE
Devise conversation recovery module

### ISSUE THREAD

**Issue by gianlucatruda** [gianlucatruda/sir2019-study-buddy-group-7#11]

**Comment by gianlucatruda** [comment]
## Method 1

```python

from studdy_buddy import InteractionException

def try_interaction(action, data, attempts=3):
    """" Conversation recovery wrapper
    """"
    retries = 0
    while retries < attempts:
        try:
            return action(data)
        except:
            raise InteractionException

def my_interaction_func(data):
    # Does stuff to the data and produce result
    return result

def alternative_flow_func():
    # Does something if the student wasn't understood


if __name__ == '__main__':
    # Try and run my function using the conversation recovery
    try:
        result = try_interaction(my_interaction_func, data)
   except InteractionException:
        alternative_flow_func()
```

## Method 2

```python
def listen_for_response():
    # ???
```

**Comment by sa-and** [comment]
Problem with that is, that the intent is always returned in the onIntend function so it is not returned in the my_interaction_func.
And onIntend is also called asyncronously

**Comment by sa-and** [comment]
def onAudioIntent(self, *args, intentName):
        # Something was understood
        self.intendUnderstood = True

        # Assuming we have a DialogueFlow app for the intent "name"
        if intentName == 'answer_name' and len(args) > 0:
            self.userName = args[0]

        self.intentLock.release()

    def ask(self, question, audioContext, attempts=3, timeout=5):
        # We only want the question to be asked once, right?
        self.sayAnimated(question)
        self.textLock.acquire()

        # new question, new stuff to understand
        self.intendUnderstood = False
        while attempts > 0 or not self.intendUnderstood:
            self.setAudioContext(audioContext)
            self.startListening()
            self.intentLock.acquire(timeout=timeout)
            self.stopListening()

            if not self.intendUnderstood:
                self.sayAnimated('Sorry, I didn\'t catch that. Could you please repeat that?')
            self.textLock.acquire()
            attempts -= 1

        if attempts == 0:
            raise InteractionException

**Comment by sa-and** [comment]
What do you think about this solution. It is in branch 11_userinp_andi
