### ISSUE TITLE
Digitise and finalise workflow diagram

### ISSUE THREAD

**Issue by gianlucatruda** [gianlucatruda/sir2019-study-buddy-group-7#2]
Create a full Draw.io version of the diagram and check that it is valid and fully-descriptive.

![image](https://user-images.githubusercontent.com/1952799/68850747-f024d300-06d4-11ea-89f3-2a07f00bb431.png)

**Comment by sa-and** [comment]
I think this is done right? @nellylojewsky and @GiuBarrios
