### ISSUE TITLE
Figure out the API and how to do the asynchronous coding on Nao

### ISSUE THREAD

**Issue by gianlucatruda** [gianlucatruda/sir2019-study-buddy-group-7#3]
# Overview

We need an example code snipped for each of the different kinds of functionality that we need to use when building our study buddy.

This way, we can map directly from the flow diagram (see issue #2) into code.

We can then document the way to do everything here so it's easier to develop independently when we don't have access to the robot.

### Speaking

```python
class SampleApplication(Base.AbstractApplication):
    def main(self):
        self.setLanguage('en-US')
        self.sayAnimated('Hello Group 7.')
        sleep(2)
```

### Standby mode (waiting for user trigger word)

**Comment by sa-and** [comment]
I would keep the documentation for this in the SampleApplication.py itself as changes are easier to track.

**Comment by gianlucatruda** [comment]
> I would keep the documentation for this in the SampleApplication.py itself as changes are easier to track.

Perhaps. But that has two downsides: 1. It doesn't support markdown, so the docs are harder to read and less informative. 2. It clutters up the code and makes it harder to separate "what things do" from "how things do it". 

Also, Github comments are actually all git repositories in their own accord—you can track and rollback changes on this comment I'm writing at the moment.

My proposed compromise on this is to create a markdown doc that we add to the repository and use as our documentation. That way we can capture all the main benefits.

**Comment by sa-and** [comment]
cool. Will do. I tried to describe it in the readme in the "Semaphores" section.
